/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4d4635",
        "surface-tint": "#735c00",
        "on-secondary-fixed": "#2e1506",
        "surface-variant": "#eee0d2",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-secondary-container": "#795541",
        "surface-container-high": "#f3e6d8",
        "on-tertiary-container": "#454543",
        "on-tertiary": "#ffffff",
        "secondary": "#7a5642",
        "surface-bright": "#fff8f3",
        "outline-variant": "#d0c5af",
        "secondary-fixed-dim": "#ecbda4",
        "on-secondary": "#ffffff",
        "on-background": "#211b12",
        "primary": "#735c00",
        "on-primary-container": "#554300",
        "inverse-primary": "#e9c349",
        "primary-container": "#d4af37",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#474744",
        "tertiary": "#5e5e5c",
        "on-error-container": "#93000a",
        "on-surface": "#211b12",
        "tertiary-fixed": "#e4e2de",
        "error-container": "#ffdad6",
        "surface-container-highest": "#eee0d2",
        "background": "#fff8f3",
        "surface": "#fff8f3",
        "tertiary-container": "#b4b3af",
        "on-primary-fixed-variant": "#574500",
        "surface-dim": "#e5d8ca",
        "surface-container": "#f9ecde",
        "inverse-surface": "#362f26",
        "inverse-on-surface": "#fcefe0",
        "on-secondary-fixed-variant": "#603f2d",
        "on-primary-fixed": "#241a00",
        "on-tertiary-fixed": "#1b1c1a",
        "primary-fixed": "#ffe088",
        "on-error": "#ffffff",
        "outline": "#7f7663",
        "primary-fixed-dim": "#e9c349",
        "secondary-fixed": "#ffdbca",
        "surface-container-low": "#fff1e3",
        "secondary-container": "#fecdb4",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "section-padding-desktop": "120px",
        "stack-lg": "32px",
        "container-max": "1140px",
        "gutter": "24px",
        "section-padding-mobile": "64px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-lg": ["DM Sans"],
        "label-caps": ["DM Sans"],
        "body-md": ["DM Sans"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "headline-md": ["Playfair Display"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
